import type { Metadata } from "next";
import { aeonik, inter, poppins } from "./fonts";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ImpersonationIndicator } from "@/components/auth/impersonation-indicator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      className={`${aeonik.variable} ${inter.variable} ${poppins.variable} antialiased`}
    >
      <body
        className="font-aeonik"
      >
        {children}
        <Toaster position="top-left" />
        <ImpersonationIndicator />
      </body>
    </html>
  );
}
