import type { Metadata } from "next";
import { aeonik, inter, manrope, poppins, satoshi } from "./fonts";
import "./globals.css";
import { AuthProvider } from "@/components/auth/auth-provider";
import { LoadingState } from "@/components/layout/loading-state";
import PageTransitions from "@/components/layout/page-transition";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${aeonik.variable} ${inter.variable} ${poppins.variable} ${satoshi.variable} ${manrope.variable} antialiased`}
		>
			<body>
				<LoadingState text="YawaTech" />
				<PageTransitions>
					<AuthProvider>{children}</AuthProvider>
				</PageTransitions>
				<Toaster position="top-center" richColors />
			</body>
		</html>
	);
}
